---
environment: production
address: 127.0.0.1
port: 8900
pid: ../../shared/pids/thin
rackup: config/config.ru
log: ../../shared/log/thin.log
max_conns: 1024
timeout: 30
max_persistent_conns: 512
daemonize: true